[package]
name = "brainfk-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.16", features = ["derive"] }

[build-dependencies]
clap = { version = "4.4.16", features = ["derive"] }
clap_mangen = "0.2.17"
project-root = "0.2.2"
