.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH brainfk-rs 1  "brainfk-rs 0.1.0" 
.SH NAME
brainfk-rs \- Brainfuck to x86_64 assembly Compiler
.SH SYNOPSIS
\fBbrainfk-rs\fR [\fB\-o\fR|\fB\-\-output\-path\fR] [\fB\-O \fR] [\fB\-S\fR|\fB\-\-assembly\fR] [\fB\-\-keep\-files\fR] [\fB\-\-ast\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIINPUT_PATH\fR> 
.SH DESCRIPTION
Brainfuck to x86_64 assembly Compiler
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\-path\fR=\fIOUTPUT_PATH\fR
Output path
.TP
\fB\-O\fR
Enable optimizations
.TP
\fB\-S\fR, \fB\-\-assembly\fR
Output generated assembly
.TP
\fB\-\-keep\-files\fR
Keep intermediate files
.TP
\fB\-\-ast\fR
Print generated AST
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
<\fIINPUT_PATH\fR>
Brainfuck source file
.SH VERSION
v0.1.0
